spring:
  config:
    activate:
      on-profile: docker
  datasource:
    url: jdbc:postgresql://${POSTGRES_HOST:postgres}:5432/${POSTGRES_DB:qvs}
    username: ${POSTGRES_USER:qvs}
    password: ${POSTGRES_PASSWORD:qvs_secret}
    driver-class-name: org.postgresql.Driver
  h2:
    console:
      enabled: false
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
